//! Architecture decision records under `docs/decisions/`. Ids are
//! `<PREFIX>-<NNNN>` with per-prefix numbering; the valid prefix set is
//! passed in by the caller (from config), falling back to the prefixes
//! already present in the tree.

use crate::error::{Error, ErrorKind};
use crate::support;
use std::fmt::Write as _;
use std::path::{Path, PathBuf};

const TEMPLATE: &str = include_str!("adr-template.md");
const INDEX_MARKER: &str = "Generated by `rune adr index`";

#[derive(Debug)]
pub struct AdrRecord {
    pub id: String,
    pub title: String,
    pub status: String,
    pub path: PathBuf,
}

pub fn decisions_dir(root: &Path) -> PathBuf {
    root.join("docs/decisions")
}

pub fn scan(root: &Path) -> Result<Vec<AdrRecord>, Error> {
    let dir = decisions_dir(root);
    let mut records = Vec::new();
    let Ok(entries) = std::fs::read_dir(&dir) else {
        return Ok(records);
    };
    for entry in entries.flatten() {
        let path = entry.path();
        let Some(name) = path.file_stem().and_then(|stem| stem.to_str()) else {
            continue;
        };
        if path.extension().and_then(|extension| extension.to_str()) != Some("md") {
            continue;
        }
        let Some((id, title)) = name.split_once(' ') else {
            continue;
        };
        if !is_adr_id(id) {
            continue;
        }
        let content = std::fs::read_to_string(&path).map_err(|error| {
            Error::new(
                ErrorKind::Io,
                format!("cannot read {}: {error}", path.display()),
            )
        })?;
        let status = frontmatter_value(&content, "status").unwrap_or_else(|| "unknown".to_string());
        records.push(AdrRecord {
            id: id.to_string(),
            title: title.to_string(),
            status,
            path,
        });
    }
    records.sort_by(|left, right| left.id.cmp(&right.id));
    Ok(records)
}

fn is_adr_id(candidate: &str) -> bool {
    match candidate.split_once('-') {
        Some((prefix, number)) => {
            !prefix.is_empty()
                && prefix.chars().all(|letter| letter.is_ascii_uppercase())
                && number.len() == 4
                && number.chars().all(|digit| digit.is_ascii_digit())
        }
        None => false,
    }
}

fn frontmatter_value(content: &str, key: &str) -> Option<String> {
    let (frontmatter, _) = support::split_frontmatter(content)?;
    for line in frontmatter.lines() {
        if let Some((candidate, value)) = line.split_once(':')
            && candidate.trim() == key
        {
            return Some(value.trim().trim_matches('"').to_string());
        }
    }
    None
}

fn allowed_prefixes(configured: Option<&str>, records: &[AdrRecord]) -> Vec<String> {
    if let Some(configured) = configured {
        return configured
            .split(',')
            .map(|prefix| prefix.trim().to_string())
            .filter(|prefix| !prefix.is_empty())
            .collect();
    }
    let mut derived: Vec<String> = records
        .iter()
        .filter_map(|record| {
            record
                .id
                .split_once('-')
                .map(|(prefix, _)| prefix.to_string())
        })
        .collect();
    derived.sort();
    derived.dedup();
    derived
}

/// Scaffold the next record for a prefix. `configured_prefixes` is the
/// comma-separated `adr.prefixes` config value when the repo sets one.
pub fn new_record(
    root: &Path,
    title: &str,
    prefix: &str,
    configured_prefixes: Option<&str>,
) -> Result<(String, PathBuf), Error> {
    if prefix.is_empty() || !prefix.chars().all(|letter| letter.is_ascii_uppercase()) {
        return Err(Error::new(
            ErrorKind::Config,
            format!("prefix must be uppercase letters only, got '{prefix}'"),
        ));
    }
    if title.is_empty()
        || title
            .chars()
            .any(|character| matches!(character, '/' | '\\' | '"' | '|' | '\n' | '\r'))
        || title.starts_with('.')
    {
        return Err(Error::new(
            ErrorKind::Config,
            "title must be plain text (no slashes, quotes, pipes, or leading dots)",
        ));
    }
    let records = scan(root)?;
    let allowed = allowed_prefixes(configured_prefixes, &records);
    if !allowed.is_empty() && !allowed.iter().any(|candidate| candidate == prefix) {
        return Err(Error::new(
            ErrorKind::Config,
            format!(
                "unknown prefix '{prefix}'; configured: {} (set adr.prefixes in config.yaml)",
                allowed.join(", ")
            ),
        ));
    }
    let id = next_id(&records, prefix);
    let date = chrono::Utc::now().format("%Y-%m-%d").to_string();
    let content = TEMPLATE
        .replace("${ID}", &id)
        .replace("${TITLE}", title)
        .replace("${DATE}", &date);
    let dir = decisions_dir(root);
    std::fs::create_dir_all(&dir).map_err(|error| {
        Error::new(
            ErrorKind::Io,
            format!("cannot create {}: {error}", dir.display()),
        )
    })?;
    let path = dir.join(format!("{id} {title}.md"));
    let mut file = std::fs::OpenOptions::new()
        .write(true)
        .create_new(true)
        .open(&path)
        .map_err(|error| {
            Error::new(
                ErrorKind::Io,
                format!("cannot create {}: {error}", path.display()),
            )
        })?;
    std::io::Write::write_all(&mut file, content.as_bytes()).map_err(|error| {
        Error::new(
            ErrorKind::Io,
            format!("cannot write {}: {error}", path.display()),
        )
    })?;
    Ok((id, path))
}

fn next_id(records: &[AdrRecord], prefix: &str) -> String {
    let next = records
        .iter()
        .filter_map(|record| {
            record
                .id
                .strip_prefix(&format!("{prefix}-"))
                .and_then(|number| number.parse::<u32>().ok())
        })
        .max()
        .unwrap_or(0)
        + 1;
    format!("{prefix}-{next:04}")
}

fn validate_prefix(prefix: &str) -> Result<(), Error> {
    if prefix.is_empty() || !prefix.chars().all(|letter| letter.is_ascii_uppercase()) {
        return Err(Error::new(
            ErrorKind::Config,
            format!("prefix must be uppercase letters only, got '{prefix}'"),
        ));
    }
    Ok(())
}

fn validate_title(title: &str) -> Result<(), Error> {
    if title.is_empty()
        || title
            .chars()
            .any(|character| matches!(character, '/' | '\\' | '"' | '|' | '\n' | '\r'))
        || title.starts_with('.')
    {
        return Err(Error::new(
            ErrorKind::Config,
            "title must be plain text (no slashes, quotes, pipes, or leading dots)",
        ));
    }
    Ok(())
}

/// One source ADR readied for this repo: the assigned id, resolved title,
/// destination-relative path, and the merged document.
#[derive(Debug)]
pub struct PreparedImport {
    pub id: String,
    pub title: String,
    pub relative: String,
    pub content: String,
}

/// Ready a foreign ADR for this repo's `docs/decisions/`: the next id in the
/// chosen prefix sequence, the title from the source frontmatter or filename
/// (any leading foreign id stripped), and frontmatter merged onto this
/// repo's ADR skeleton — source values win where keys overlap, extra source
/// keys survive, and the body lands verbatim so a review sees what upstream
/// wrote. The source's own id continues only in provenance, never in the
/// destination sequence.
pub fn prepare_import(
    root: &Path,
    source_content: &str,
    source_stem: &str,
    prefix: &str,
) -> Result<PreparedImport, Error> {
    validate_prefix(prefix)?;
    let (source_frontmatter, source_body) = match support::split_frontmatter(source_content) {
        Some((frontmatter, body)) => (Some(frontmatter), body),
        None => (None, source_content),
    };

    let source_mapping: serde_yaml::Mapping = source_frontmatter
        .and_then(|raw| serde_yaml::from_str::<serde_yaml::Value>(raw).ok())
        .and_then(|value| value.as_mapping().cloned())
        .unwrap_or_default();

    let title = source_mapping
        .get(serde_yaml::Value::String("title".to_string()))
        .and_then(|value| value.as_str())
        .map_or_else(|| title_from_stem(source_stem), str::to_string);
    validate_title(&title)?;

    let records = scan(root)?;
    let id = next_id(&records, prefix);
    let date = chrono::Utc::now().format("%Y-%m-%d").to_string();

    let skeleton = TEMPLATE
        .replace("${TITLE}", &title)
        .replace("${DATE}", &date);
    let (skeleton_frontmatter, _) = support::split_frontmatter(&skeleton)
        .ok_or_else(|| Error::new(ErrorKind::Parse, "ADR template lost its frontmatter"))?;
    let mut merged: serde_yaml::Mapping =
        serde_yaml::from_str::<serde_yaml::Value>(skeleton_frontmatter)
            .ok()
            .and_then(|value| value.as_mapping().cloned())
            .ok_or_else(|| {
                Error::new(
                    ErrorKind::Parse,
                    "ADR template frontmatter is not a mapping",
                )
            })?;
    for (key, value) in &source_mapping {
        merged.insert(key.clone(), value.clone());
    }
    merged.insert(
        serde_yaml::Value::String("title".to_string()),
        serde_yaml::Value::String(title.clone()),
    );

    let frontmatter_yaml =
        serde_yaml::to_string(&serde_yaml::Value::Mapping(merged)).map_err(|error| {
            Error::new(
                ErrorKind::Parse,
                format!("cannot serialize frontmatter: {error}"),
            )
        })?;

    let mut body = source_body.trim_start_matches('\n').to_string();
    if !body.lines().any(|line| line.starts_with("# ")) {
        body = format!("# {title}\n\n{body}");
    }
    if !body.ends_with('\n') {
        body.push('\n');
    }

    let content = format!("---\n{frontmatter_yaml}---\n\n{body}");
    let relative = format!("docs/decisions/{id} {title}.md");
    Ok(PreparedImport {
        id,
        title,
        relative,
        content,
    })
}

/// `"ARCH-0007 Launch Profiles"` → `"Launch Profiles"`; a stem without a
/// leading ADR id stays whole.
fn title_from_stem(stem: &str) -> String {
    match stem.split_once(' ') {
        Some((first, rest)) if is_adr_id(first) && !rest.is_empty() => rest.to_string(),
        _ => stem.to_string(),
    }
}

/// Flip `old` to superseded and cross-link both records' `related:` lists.
pub fn supersede(root: &Path, old: &str, new: &str) -> Result<(), Error> {
    if old == new {
        return Err(Error::new(
            ErrorKind::Config,
            format!("{old} cannot supersede itself"),
        ));
    }
    let records = scan(root)?;
    let find = |id: &str| {
        records
            .iter()
            .find(|record| record.id == id)
            .ok_or_else(|| Error::new(ErrorKind::Config, format!("no decision with id {id}")))
    };
    let old_record = find(old)?;
    let new_record = find(new)?;

    let old_stem = format!("{} {}", old_record.id, old_record.title);
    let new_stem = format!("{} {}", new_record.id, new_record.title);

    // Precompute both rewrites so a parse failure on either record aborts
    // before any file changes.
    let old_content = rewritten_frontmatter(&old_record.path, |frontmatter| {
        let updated = set_frontmatter_status(frontmatter, "superseded");
        append_related(&updated, &new_stem)
    })?;
    let new_content = rewritten_frontmatter(&new_record.path, |frontmatter| {
        append_related(frontmatter, &old_stem)
    })?;
    support::write_atomic_all(&[
        (&old_record.path, &old_content),
        (&new_record.path, &new_content),
    ])
    .map_err(|message| Error::new(ErrorKind::Io, message))
}

fn rewritten_frontmatter(path: &Path, transform: impl Fn(&str) -> String) -> Result<String, Error> {
    let content = std::fs::read_to_string(path).map_err(|error| {
        Error::new(
            ErrorKind::Io,
            format!("cannot read {}: {error}", path.display()),
        )
    })?;
    let Some((frontmatter, body)) = support::split_frontmatter(&content) else {
        return Err(Error::new(
            ErrorKind::Parse,
            format!("{} has no frontmatter", path.display()),
        ));
    };
    Ok(format!("---\n{}---\n{body}", transform(frontmatter)))
}

fn set_frontmatter_status(frontmatter: &str, status: &str) -> String {
    let mut lines: Vec<String> = Vec::new();
    let mut replaced = false;
    for line in frontmatter.lines() {
        // Only the top-level key: nested status fields keep their indentation.
        if line.starts_with("status:") {
            lines.push(format!("status: {status}"));
            replaced = true;
        } else {
            lines.push(line.to_string());
        }
    }
    if !replaced {
        lines.push(format!("status: {status}"));
    }
    let mut joined = lines.join("\n");
    joined.push('\n');
    joined
}

fn append_related(frontmatter: &str, stem: &str) -> String {
    if frontmatter.contains(stem) {
        let mut unchanged = frontmatter.to_string();
        if !unchanged.ends_with('\n') {
            unchanged.push('\n');
        }
        return unchanged;
    }
    let entry = format!("    - \"{stem}\"");
    let mut lines: Vec<String> = frontmatter.lines().map(str::to_string).collect();
    if let Some(position) = lines.iter().position(|line| line.starts_with("related:")) {
        let existing = lines[position].trim();
        if existing == "related: []" {
            lines[position] = "related:".to_string();
            lines.insert(position + 1, entry);
        } else if let Some(inline) = existing
            .strip_prefix("related: [")
            .and_then(|rest| rest.strip_suffix(']'))
        {
            // Inline flow lists stay inline.
            lines[position] = format!("related: [{inline}, \"{stem}\"]");
        } else {
            lines.insert(position + 1, entry);
        }
    } else {
        lines.push("related:".to_string());
        lines.push(entry);
    }
    let mut joined = lines.join("\n");
    joined.push('\n');
    joined
}

/// Regenerate the decisions index table. Refuses to overwrite a README the
/// index did not generate.
pub fn index(root: &Path) -> Result<(usize, PathBuf), Error> {
    let records = scan(root)?;
    let mut table = String::from(
        "# Decisions\n\nGenerated by `rune adr index`.\n\n| Id | Title | Status |\n|----|-------|--------|\n",
    );
    for record in &records {
        let _ = writeln!(
            table,
            "| {} | [{}]({}) | {} |",
            record.id,
            record.title,
            urlencoded_basename(&record.path),
            record.status
        );
    }
    let path = decisions_dir(root).join("README.md");
    if path.is_file() {
        let existing = std::fs::read_to_string(&path).map_err(|error| {
            Error::new(
                ErrorKind::Io,
                format!("cannot read {}: {error}", path.display()),
            )
        })?;
        if !existing.contains(INDEX_MARKER) {
            return Err(Error::new(
                ErrorKind::Config,
                format!(
                    "{} exists and was not generated by rune adr index; move it aside first",
                    path.display()
                ),
            ));
        }
    }
    support::write_atomic(&path, &table).map_err(|message| Error::new(ErrorKind::Io, message))?;
    Ok((records.len(), path))
}

fn urlencoded_basename(path: &Path) -> String {
    path.file_name()
        .map(|name| name.to_string_lossy().replace(' ', "%20"))
        .unwrap_or_default()
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    #[test]
    fn prepare_import_assigns_next_id_and_strips_foreign_id_from_stem() {
        let root = TempDir::new().unwrap();
        let dir = decisions_dir(root.path());
        std::fs::create_dir_all(&dir).unwrap();
        std::fs::write(
            dir.join("CLI-0001 Existing.md"),
            "---\nstatus: accepted\n---\n# Existing\n",
        )
        .unwrap();

        let prepared = prepare_import(
            root.path(),
            "# Launch Profiles\n\nBody.\n",
            "ARCH-0007 Launch Profiles",
            "CLI",
        )
        .unwrap();

        assert_eq!(prepared.id, "CLI-0002");
        assert_eq!(prepared.title, "Launch Profiles");
        assert_eq!(
            prepared.relative,
            "docs/decisions/CLI-0002 Launch Profiles.md"
        );
    }

    #[test]
    fn prepare_import_merges_source_frontmatter_over_the_skeleton() {
        let root = TempDir::new().unwrap();
        let source = "---\ntitle: \"Chosen Title\"\nstatus: accepted\ncustom: kept\n---\n\n# Chosen Title\n\nWhy.\n";

        let prepared = prepare_import(root.path(), source, "ignored-stem", "ARCH").unwrap();

        let (frontmatter, body) = support::split_frontmatter(&prepared.content).unwrap();
        let value: serde_yaml::Value = serde_yaml::from_str(frontmatter).unwrap();
        assert_eq!(value["title"].as_str(), Some("Chosen Title"));
        assert_eq!(value["status"].as_str(), Some("accepted"));
        assert_eq!(value["custom"].as_str(), Some("kept"));
        assert_eq!(value["type"].as_str(), Some("adr"));
        assert!(value.get("responsible").is_some(), "skeleton keys survive");
        assert!(body.contains("# Chosen Title"));
        assert!(body.contains("Why."));
    }

    #[test]
    fn prepare_import_prepends_a_heading_when_the_source_has_none() {
        let root = TempDir::new().unwrap();

        let prepared = prepare_import(
            root.path(),
            "Just prose, no heading.\n",
            "Bare Notes",
            "CLI",
        )
        .unwrap();

        let (_, body) = support::split_frontmatter(&prepared.content).unwrap();
        assert!(body.trim_start().starts_with("# Bare Notes"));
    }

    #[test]
    fn prepare_import_rejects_a_lowercase_prefix() {
        let root = TempDir::new().unwrap();
        let error = prepare_import(root.path(), "# X\n", "X", "cli").unwrap_err();
        assert!(error.message().contains("uppercase"));
    }
}
